# Serving certificate for the conversion webhook. SERVICE_NAME and
# SERVICE_NAMESPACE are filled in by the replacements in config/default.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: application-upgrade-operator
    app.kubernetes.io/managed-by: kustomize
  name: serving-cert
  namespace: system
spec:
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
